// src/lib/sampleBookings.js

export const sampleBookings = [
  {
    id: "BC-1001",
    name: "Bruce Thiombiano",
    service: "Deep Cleaning",
    location: "East Legon",
    dateTime: "2025-10-05 10:00",
    amount: 450,
    status: "confirmed",
    payment: "paid",
  },
  {
    id: "BC-1002",
    name: "Ama Mensah",
    service: "House Cleaning",
    location: "Labone",
    dateTime: "2025-10-06 14:00",
    amount: 350,
    status: "pending",
    payment: "unpaid",
  },
  {
    id: "BC-1003",
    name: "Kojo Adjei",
    service: "Carpet Cleaning",
    location: "Osu",
    dateTime: "2025-10-07 09:30",
    amount: 250,
    status: "in_progress",
    payment: "paid",
  },
  {
    id: "BC-1004",
    name: "Selina Owusu",
    service: "Post Construction Cleaning",
    location: "Airport Residential",
    dateTime: "2025-10-08 11:00",
    amount: 600,
    status: "completed",
    payment: "paid",
  },
  {
    id: "BC-1005",
    name: "Kwame Boateng",
    service: "House Cleaning",
    location: "Osu",
    dateTime: "2025-10-09 16:00",
    amount: 300,
    status: "cancelled",
    payment: "refunded",
  },
  {
    id: "BC-1006",
    name: "Linda Afriyie",
    service: "Deep Cleaning",
    location: "East Legon",
    dateTime: "2025-10-10 13:00",
    amount: 500,
    status: "confirmed",
    payment: "paid",
  },
];
